import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,User,ShoppingCart,Plus,Star,MessageCircle,Bell,Wallet,ShieldCheck,Clock,ArrowRight,Menu,X,Briefcase,Heart,CheckCircle} from 'lucide-react';
import './styles.css';

const initialServices=[
{id:1,title:'Criação de logo profissional',seller:'Studio Design',price:89,delivery:3,category:'Design',rating:4.9,reviews:124,image:'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80'},
{id:2,title:'Edição de vídeos para Instagram e TikTok',seller:'VideoPro',price:120,delivery:2,category:'Vídeo',rating:4.8,reviews:87,image:'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80'},
{id:3,title:'Criação de site profissional',seller:'WebMaster BR',price:350,delivery:7,category:'Programação',rating:5,reviews:56,image:'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=900&q=80'},
{id:4,title:'Locução profissional em português',seller:'Voz Brasil',price:75,delivery:2,category:'Áudio',rating:4.9,reviews:103,image:'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80'},
{id:5,title:'Gestão de Instagram por 30 dias',seller:'Social Expert',price:280,delivery:5,category:'Marketing',rating:4.7,reviews:41,image:'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80'},
{id:6,title:'Currículo profissional e LinkedIn',seller:'Carreira Fácil',price:59,delivery:2,category:'Escrita',rating:4.9,reviews:210,image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80'}
];

function App(){
 const [services,setServices]=useState(initialServices),[page,setPage]=useState('home'),[search,setSearch]=useState(''),[category,setCategory]=useState('Todas'),[cart,setCart]=useState([]),[balance,setBalance]=useState(0),[user,setUser]=useState(null),[mobile,setMobile]=useState(false),[selected,setSelected]=useState(null),[showLogin,setShowLogin]=useState(false),[showPublish,setShowPublish]=useState(false);
 const filtered=services.filter(s=>(category==='Todas'||s.category===category)&&(!search||s.title.toLowerCase().includes(search.toLowerCase())));
 const buy=s=>{if(balance<s.price){alert('Adicione saldo à sua carteira para comprar este serviço.');setPage('wallet');return}setBalance(b=>b-s.price);setCart(c=>[...c,s]);alert('Compra realizada! O valor ficará retido até a entrega do serviço.');};
 const publish=e=>{e.preventDefault();const f=new FormData(e.currentTarget);setServices(x=>[{id:Date.now(),title:f.get('title'),seller:'Você',price:Number(f.get('price')),delivery:Number(f.get('delivery')),category:f.get('category'),rating:0,reviews:0,image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80'},...x]);setShowPublish(false);alert('Serviço publicado com sucesso!');};
 return <div className="app">
  <header><div className="nav container"><button className="brand" onClick={()=>setPage('home')}><span>J</span> FAZ PRA MIM</button><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="O que você precisa hoje?"/></div><nav className={mobile?'open':''}><button onClick={()=>{setPage('home');setMobile(false)}}>Explorar</button><button onClick={()=>setShowPublish(true)}>Vender serviço</button><button onClick={()=>setPage('dashboard')}>Meus pedidos</button></nav><div className="actions"><button onClick={()=>setPage('wallet')} title="Carteira"><Wallet size={20}/><small>R$ {balance.toFixed(2)}</small></button><button onClick={()=>setPage('cart')} className="iconBtn"><ShoppingCart size={20}/>{cart.length>0&&<b>{cart.length}</b>}</button><button onClick={()=>setShowLogin(true)} className="profile"><User size={20}/><span>{user?'Minha conta':'Entrar'}</span></button><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></div></header>
  <main>
  {page==='home'&&<><section className="hero"><div className="container heroGrid"><div><div className="pill"><CheckCircle size={16}/> Marketplace brasileiro de freelancers</div><h1>Encontre quem faz.<br/><em>Publique o que você sabe.</em></h1><p>Contrate profissionais independentes ou transforme suas habilidades em renda.</p><div className="heroSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex.: criar logo, editar vídeo..."/><button onClick={()=>document.getElementById('servicos').scrollIntoView({behavior:'smooth'})}>Buscar</button></div><div className="trust"><ShieldCheck size={18}/> Pagamento protegido até a entrega <span>•</span> Suporte seguro</div></div><div className="heroCard"><div className="heroStat"><strong>+10 mil</strong><span>serviços disponíveis</span></div><div className="heroStat"><strong>R$ 0</strong><span>para criar sua conta</span></div><div className="heroStat"><strong>15%</strong><span>taxa da plataforma</span></div></div></div></section>
  <section className="categories container"><button className={category==='Todas'?'active':''} onClick={()=>setCategory('Todas')}>Todos</button>{['Design','Programação','Marketing','Vídeo','Áudio','Escrita'].map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</section>
  <section id="servicos" className="container section"><div className="sectionHead"><div><span className="eyebrow">EXPLORE</span><h2>Serviços em destaque</h2></div><button className="linkBtn">Ver todos <ArrowRight size={16}/></button></div><div className="grid">{filtered.map(s=><ServiceCard key={s.id} s={s} onOpen={()=>setSelected(s)} onBuy={()=>buy(s)}/>)}</div></section>
  <section className="sellBanner container"><div><span className="eyebrow">PARA FREELANCERS</span><h2>Transforme seu talento em renda</h2><p>Crie seu serviço, defina seu preço e encontre novos clientes.</p><button onClick={()=>setShowPublish(true)}>Publicar meu serviço <ArrowRight size={17}/></button></div><Briefcase size={110}/></section></>}
  {page==='wallet'&&<WalletPage balance={balance} setBalance={setBalance}/>}
  {page==='cart'&&<Cart cart={cart} setCart={setCart} balance={balance} setBalance={setBalance}/>}
  {page==='dashboard'&&<Dashboard services={services.filter(s=>s.seller==='Você')} onPublish={()=>setShowPublish(true)}/>}
  </main>
  <footer><div className="container footerGrid"><div><button className="brand"><span>J</span> FAZ PRA MIM</button><p>O marketplace brasileiro para serviços digitais.</p></div><div><strong>Para clientes</strong><a>Como funciona</a><a>Comprar serviços</a><a>Segurança</a></div><div><strong>Para freelancers</strong><a>Vender serviços</a><a>Taxas</a><a>Central de ajuda</a></div><div><strong>Proteção</strong><p><ShieldCheck size={16}/> Pagamentos retidos até a entrega.</p></div></div><div className="copyright">© 2026 FAZ PRA MIM. Plataforma demonstrativa.</div></footer>
  {selected&&<Modal onClose={()=>setSelected(null)}><img className="detailImg" src={selected.image}/><div className="detailBody"><span className="tag">{selected.category}</span><h2>{selected.title}</h2><p>Serviço profissional feito sob medida. Combine os detalhes com o freelancer pelo chat e acompanhe a entrega pela plataforma.</p><div className="seller"><div className="avatar">{selected.seller[0]}</div><div><strong>{selected.seller}</strong><span>★ {selected.rating||'Novo'} ({selected.reviews} avaliações)</span></div></div><div className="detailBottom"><div><small>A partir de</small><strong>R$ {selected.price.toFixed(2)}</strong><span><Clock size={15}/> {selected.delivery} dias</span></div><button onClick={()=>{setSelected(null);buy(selected)}}>Comprar agora</button></div></div></Modal>}
  {showLogin&&<Modal onClose={()=>setShowLogin(false)}><div className="formBox"><h2>Entrar no FAZ PRA MIM</h2><p>Acesse sua conta ou crie uma nova gratuitamente.</p><input placeholder="E-mail"/><input placeholder="Senha" type="password"/><button onClick={()=>{setUser({name:'Usuário'});setShowLogin(false)}}>Entrar</button><small>Ao conectar um backend, estes campos serão ligados à autenticação segura.</small></div></Modal>}
  {showPublish&&<Modal onClose={()=>setShowPublish(false)}><form className="formBox" onSubmit={publish}><h2>Publicar serviço</h2><input name="title" required placeholder="Título do serviço"/><textarea name="description" placeholder="Descreva detalhadamente o que você entrega"/><div className="two"><select name="category"><option>Design</option><option>Programação</option><option>Marketing</option><option>Vídeo</option><option>Áudio</option><option>Escrita</option></select><input name="price" required type="number" min="1" placeholder="Preço (R$)"/></div><input name="delivery" required type="number" min="1" placeholder="Prazo em dias"/><input type="file" accept="image/*,video/*" multiple/><button type="submit">Publicar serviço</button></form></Modal>}
 </div>
}
function ServiceCard({s,onOpen,onBuy}){return <article className="card"><div className="cardImg" onClick={onOpen}><img src={s.image}/><button className="heart"><Heart size={18}/></button></div><div className="cardBody"><span className="tag">{s.category}</span><h3 onClick={onOpen}>{s.title}</h3><div className="sellerMini"><div className="avatar">{s.seller[0]}</div><span>{s.seller}</span></div><div className="rating"><Star size={15} fill="currentColor"/><b>{s.rating||'Novo'}</b><span>({s.reviews})</span></div><div className="price"><div><small>a partir de</small><strong>R$ {s.price.toFixed(2)}</strong></div><button onClick={onBuy}>Comprar</button></div></div></article>}
function Modal({children,onClose}){return <div className="overlay" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="close" onClick={onClose}><X/></button>{children}</div></div>}
function WalletPage({balance,setBalance}){const [value,setValue]=useState('');return <section className="container page"><div className="pageTitle"><span className="eyebrow">CARTEIRA</span><h1>Seu saldo</h1><p>Adicione saldo para comprar serviços. O valor da compra fica retido até a entrega.</p></div><div className="walletCard"><Wallet size={34}/><small>Saldo disponível</small><strong>R$ {balance.toFixed(2)}</strong><div className="add"><input type="number" value={value} onChange={e=>setValue(e.target.value)} placeholder="Valor para adicionar"/><button onClick={()=>{setBalance(b=>b+Number(value||0));setValue('')}}>Adicionar saldo</button></div></div><div className="infoGrid"><div><ShieldCheck/><h3>Pagamento protegido</h3><p>O dinheiro permanece retido até a confirmação da entrega.</p></div><div><Clock/><h3>Liberação</h3><p>Após a entrega e confirmação do pedido, o valor é liberado ao freelancer.</p></div><div><Briefcase/><h3>Taxa transparente</h3><p>A plataforma desconta 15% do valor de cada venda.</p></div></div></section>}
function Cart({cart,setCart,balance,setBalance}){const total=cart.reduce((a,s)=>a+s.price,0),fee=total*.1;return <section className="container page"><div className="pageTitle"><span className="eyebrow">CARRINHO</span><h1>Seus serviços</h1></div>{!cart.length?<div className="empty"><ShoppingCart size={48}/><h2>Seu carrinho está vazio</h2><p>Explore os serviços disponíveis e encontre seu próximo freelancer.</p></div>:<div className="cartLayout"><div>{cart.map((s,i)=><div className="cartItem" key={i}><img src={s.image}/><div><h3>{s.title}</h3><span>{s.seller} • {s.delivery} dias</span></div><strong>R$ {s.price.toFixed(2)}</strong><button onClick={()=>setCart(c=>c.filter((_,x)=>x!==i))}><X/></button></div>)}</div><aside className="summary"><h3>Resumo</h3><p>Serviços <b>R$ {total.toFixed(2)}</b></p><p>Proteção <b>Incluída</b></p><hr/><h2>Total <strong>R$ {total.toFixed(2)}</strong></h2><button onClick={()=>{if(balance<total)return alert('Saldo insuficiente. Adicione saldo na carteira.');setBalance(b=>b-total);setCart([]);alert('Pedido confirmado!')}}>Finalizar compra</button><small>A taxa de 15% é descontada do vendedor, não do comprador.</small></aside></div>}</section>}
function Dashboard({services,onPublish}){return <section className="container page"><div className="pageTitle"><span className="eyebrow">PAINEL</span><h1>Minha área</h1><p>Gerencie seus pedidos, vendas e serviços publicados.</p></div><div className="dashStats"><div><ShoppingCart/><strong>0</strong><span>Pedidos ativos</span></div><div><Briefcase/><strong>{services.length}</strong><span>Serviços publicados</span></div><div><MessageCircle/><strong>0</strong><span>Mensagens</span></div><div><Star/><strong>—</strong><span>Avaliação</span></div></div><div className="panel"><div className="sectionHead"><h2>Meus serviços</h2><button onClick={onPublish}>+ Publicar serviço</button></div>{services.length?services.map(s=><div className="miniService"><img src={s.image}/><div><strong>{s.title}</strong><span>R$ {s.price.toFixed(2)} • {s.delivery} dias</span></div><span className="status">Ativo</span></div>):<div className="empty small"><Briefcase/><p>Você ainda não publicou nenhum serviço.</p><button onClick={onPublish}>Criar meu primeiro serviço</button></div>}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);